spring:
  datasource:
    url: jdbc:mysql://localhost:3306/imdb
    username: root
    password: password


  jpa:

    hibernate:
      ddl-auto: update
    show-sql: true

    defer-datasource-initialization: true

  sql:
    init:
      mode: never


